 # PostgreSQL Configuration
postgresql.driver=org.postgresql.Driver
postgresql.url=jdbc:postgresql://localhost:5432/library_db
postgresql.user=postgres
postgresql.password=Join0253

# Active database
active.db=postgresql